# Note that only one of these targets is required

open_melting_point_dataset:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: materialscience-dev
      dataset:  raw_data # You can also use "schema" here
      threads: 1
      keyfile: /secrets/dbt-secret-keyfile
      # location: us-east1
      # [<optional_config>](#optional-configurations): <value>
    
    # prod:
    #   type: bigquery
    #   method: service-account
    #   project: materialscience-prod
    #   dataset:  prod # You can also use "schema" here
    #   threads: 1
    #   keyfile: /secrets/dbt-secret-keyfile
    #   location: us-east1
      # [<optional_config>](#optional-configurations): <value>