# Note that only one of these targets is required

my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: meltingpointprediction
      dataset: dataset001_meltingpointprediction # You can also use "schema" here
      threads: 1
      [<optional_config>](#optional-configurations): <value>