# Note that only one of these targets is required

my-bigquery-db:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: meltingpointprediction
      dataset: dataset001_meltingpointprediction # You can also use "schema" here
      threads: 1
      keyfile: /secrets/dbt-service-keyfile
      # [<optional_config>](#optional-configurations): <value>